site_name: SeqCol
site_logo: img/seqcol_.svg
site_url: http://seqcol.databio.org/
repo_url: http://github.com/refgenie/seqcol
pypi_name: seqcol

nav:
  - Getting Started: 
    - Introduction: README.md
    - Motivation: motivation.md
    - Install and configure: install.md
  - How-to Guides:
    - "Tutorial": tutorial.md
    - Write a manifest: manifest.md
  - Reference:
    - Support: https://github.com/refgenie/seqcol/issues
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      no_top_level: true
  - search
